FROM themrdemonized/vsgan_tensorrt:1.5
RUN cd /usr/local/include/vapoursynth && git clone https://github.com/Kiyamou/VapourSynth-AreaResize && cd VapourSynth-AreaResize/AreaResize/ && mv AreaResize.cpp ../../AreaResize.cpp && cd ../../ && g++ -shared -fPIC -O2 AreaResize.cpp -o AreaResize.so && rm -f AreaResize.cpp && rm -rf VapourSynth-AreaResize
WORKDIR /workspace/tensorrt
