FROM themrdemonized/vsgan_tensorrt:1.0
RUN git clone https://github.com/HomeOfVapourSynthEvolution/VapourSynth-CAS && cd VapourSynth-CAS && meson build && ninja -C build && ninja -C build install && cd .. && rm -rf VapourSynth-CAS
WORKDIR /workspace/tensorrt
