FROM themrdemonized/vsgan_tensorrt:1.1
RUN git clone https://github.com/styler00dollar/vs-gmfss_fortuna && cd vs-gmfss_fortuna && pip install . && cd .. && rm -rf vs-gmfss_fortuna
RUN git clone https://github.com/styler00dollar/vs-dpir && cd vs-dpir && pip install . && cd .. && rm -rf vs-dpir
WORKDIR /workspace/tensorrt
